SERVICE_ACCOUNT_FILE = "credentials-example.json"

[SPREADSHEET]
#https://docs.google.com/spreadsheets/d/1GC8hgtn_2ernrsacQWmr3ngRVMmx4dFM9jdhe1_0GW8/
ID = "1GC8hgtn_2ernrsacQWmr3ngRVMmx4dFM9jdhe1_0GW8" #spreadsheetId
RANGE = "Class Data!A2:F31" #worksheetName and range
# mapping of the column names (should contain an item for every column in the range)
COLUMN_NAMES = ["student", "gender", "class_level", "home_state", "major", "extracurricular_activity"]
